# Generated by Django 4.1.3 on 2023-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('F', 'Food'), ('H', 'Health'), ('T', 'Training'), ('O', 'Other')], default='F', max_length=10),
        ),
    ]
